////

|metadata|
{
    "name": "excelengine-api-overview",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{C5F8A2E9-7CD6-4B00-9EA6-B26EFA48DEA8}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:18:50Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the code library. We also give you several key classes that you will be using while programming with this code library. The namespaces and classes on this page link directly into our API documentation.

=== Infragistics Excel Engine Namespace:

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel_namespace.html[Infragistics.Documents.Excel]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel_namespace.html[Infragistics.Documents.Excel]"]

=== Key Classes:

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties.html[DocumentProperties]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties.html[DocumentProperties]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbookwindowoptions.html[WorkbookWindowOptions]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet.html[Worksheet]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetrow.html[WorksheetRow]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcolumn.html[WorksheetColumn]"]

pick:[win-forms="link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]
pick:[asp-net="link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]