////

|metadata|
{
    "name": "excelengine-write-a-workbook-to-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{79EEEA27-98FC-4115-AE79-4B2C3FF92C1E}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:23:47Z"
}
|metadata|
////

= Write a Workbook to an Excel File

After setting all options and cell values, the last thing you need to do with your workbook is write it to a file so it can be opened in Microsoft® Excel®. This is easily performed with the  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Save]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Save]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Save]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~save.html[Save]"]  method of  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook.html[Workbook]"]  object. You can write the workbook to a stream or have it automatically create an xls file for itself.

.Note
[NOTE]
====
Before saving a workbook, it must contain at least one visible worksheet; otherwise, an exception will be thrown when the Save method is called.
====

The following code shows how to write your workbook to a file once you are done creating it.

*In Visual Basic:*

----
workbook.Save("C:\Orders.xls")
----

*In C#:*

----
workbook.Save( "C:\\Orders.xls" );
----