////

|metadata|
{
    "name": "excelengine-getting-the-value-of-a-formula-from-an-excel-file",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{DC254CCD-E36D-4C9C-8064-DE6F151EA44B}",  
    "buildFlags": [],
    "createdOn": "2008-11-09T11:33:27Z"
}
|metadata|
////

= Getting the Value of a Formula from an Excel File

In order to get the evaluated value of an Excel Cell that is represented by a Formula, you simply access the  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell~value.html[Value]"]pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell~value.html[Value]"]  property of the  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"]pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheetcell.html[WorksheetCell]"] .

The example code below shows you how to access a particular Excel Worksheet Cell that is populated by an Excel Formula.

*In Visual Basic:*

----
lblValue.Text = theWorksheet.Rows[1].Cells[4].Value;
----

*In C#:*

----
lblValue.Text = theWorksheet.Rows[1].Cells[4].Value;
----

== Related Topics

link:excelengine-read-an-excel-file-into-a-workbook.html[Read an Excel File into a Workbook]

pick:[win-forms="link:wingrid-getting-excel-formula-values-into-wingrid.html[Getting Excel Formula Values into WinGrid]"]