////

|metadata|
{
    "name": "excelengine-accessing-cells-and-regions-by-their-reference-strings",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{B8228DFD-7B7B-4332-AC1F-F4B84D454524}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Accessing Cells and Regions by their Reference Strings

This topic will familiarize you on how to access cells and ranges within a worksheet in an Excel® Workbook. The  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getcell.html[GetCell]"]  and  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.worksheet~getregion.html[GetRegion]"]  method of the Worksheet class accepts cell reference strings as a parameter.

In the following example code a Worksheet cell is accessed by the GetCell method and an Excel formula is applied to it. Similarly an Excel formula is applied to a range of cells within the worksheet.

*In Visual Basic:*

----
'Accessing a single cell
worksheet.GetCell ("C5").ApplyFormula ("=A5*B5")
'Accessing a range of cells
 worksheet.GetRegion ("G1:G10").ApplyFormula ("=E1*F1")
----

*In C#:*

----
//Accessing a single cell
worksheet.GetCell ("C5").ApplyFormula ("=A5*B5");
//Accessing a range of cells
 worksheet.GetRegion ("G1:G10").ApplyFormula ("=E1*F1");
----