////

|metadata|
{
    "name": "excelengine-add-document-properties-to-a-workbook",
    "controlName": ["Infragistics Excel Engine"],
    "tags": [],
    "guid": "{68A2E8C6-AEE0-406F-AA41-4C23D98A63DD}",  
    "buildFlags": [],
    "createdOn": "2007-04-05T08:21:11Z"
}
|metadata|
////

= Add Document Properties to a Workbook

Associated with each workbook file are various properties that provide information about its content. These properties include the following pieces of information:

* Author
* Title
* Subject
* Keywords
* Category
* Status
* Comments

This information can be accessed through the Microsoft® Excel® interface as well as the Properties dialog box for the workbook file. You can edit this information in a workbook before serializing it by using its  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.workbook~documentproperties.html[DocumentProperties]"]  property.

The following code demonstrates how to create a workbook and set its  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~title.html[Title]"]  and  pick:[win-forms=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.excel{ApiVersion}~infragistics.documents.excel.documentproperties~status.html[Status]"]  document properties.

*In Visual Basic:*

----
Dim workbook As New Infragistics.Documents.Excel.Workbook()
workbook.DocumentProperties.Title = "Expense Report"
workbook.DocumentProperties.Status = "Complete"
----

*In C#:*

----
Infragistics.Documents.Excel.Workbook workbook = new Infragistics.Documents.Excel.Workbook();
workbook.DocumentProperties.Title = "Expense Report";
workbook.DocumentProperties.Status = "Complete";
----